# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c73ebf1a6980b3ba4326442e9f475392f43cb4dcfb179cf7b60774e974be72b02e11cc6177bda3d96447b9b772c4b4f52666fb770217e2ac7d852aaaaf8e0d61

test:
  secret_key_base: 5636a7421cfdd3c22d14f7dc6f5e49b080fadbb4eefb7a26a9c78cb1eea5657ba0cc41cf94ca517b4d4a2d32cc97ac2d2b460474a774098af12fb04eb64b4109

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
